### ISSUE TITLE
Swapped UriPath options when using custom ICoapEndpoint

### ISSUE THREAD

**Issue by malachib** [NZSmartie/CoAP.Net#11]
When utilizing a specialized ICoapEndpoint transport layer, what begins as:

UriPath: v1
UriPath: version

in CoapMessage becomes swapped in the outgoing bytes in the CoapPacket I receive during ICoapEndpoint.SendAsync service call.  i.e. *version* appears before *v1*.  UriPath is output in expected order when using Udp endpoint.

Roll a unit-y test just utilizing CoapOption list + CoapMessage.GetBytes to reproduce the issue but that spat out options in expected order.  So I'm kinda stumped

It's definitely reproducable in our executing program that we're writing

**Comment by NZSmartie** [comment]
That's a bit strange. SendAsync's signature is `Task SendAsync(CoapPacket)` where `CoapPacket.Payload` is the serialised `CoapMessage`.  
So Payload is handled as opaque (meaning not parsed or modified in anyway). 

When a message is serialised through `CoapMessage.ToBytes()`, the message's options are sorted only based on the option number, sequential options with the same option number should have their order preserved. (This is done by implementing `IComparable<CoapOption>` in [CoapOption.cs](https://github.com/NZSmartie/CoAP.Net/blob/71cffd7/src/CoAPNet/CoapOptions.cs#L475-L478))

Could you test again but include ALL the options in your CoapMessage? not just `UriPath` I think the ordering may be affecting how the options are sorted. which i'll look into.

**Comment by malachib** [comment]
Yeah willdo.  Totally forgot to include UriHost, which is present in the failing condition.  I found it peculiar too for the reasons you describe.  The code is opaque, and UriHost does appear in the right place in all conditions... feels like a bug in MY code, but... well, I already looked there !

**Comment by malachib** [comment]
Tossed UriHost in there but no change.  I'm gonna double down on testing my own code, will get back to you

**Comment by NZSmartie** [comment]
Looking into this further. The [`List<T>.Sort()`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.sort?view=netstandard-1.3) method is an unstable sort, which means elements of the same value are not guaranteed to end up in the same order a before. An alternative is to use [`Enumerable.OrderBy()`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderby?view=netstandard-1.3) which is stable.

**Comment by malachib** [comment]
We may have found our culprit then.  My synthetic test always produces proper results, but on deeper inspection on our active code, I can verify indeed the List<Options> itself is being shuffled backward, not just the byte payload

EDIT: Looking forward to trying your code tomorrow :)

**Comment by NZSmartie** [comment]
Fixed and released in v0.5.2, should be available on NuGet shortly
