### ISSUE TITLE
CoapClient ReceiveAsync can't be canceld using a CancellationToken

### ISSUE THREAD

**Issue by CrazyOrange** [NZSmartie/CoAP.Net#17]
It seems that it's not possible to cancel a CoapClient ReceiveAsync call by cancling the CancellationToken.

**Comment by NZSmartie** [comment]
Are you able to provide sample application where ReceiveAsync does not throw a OperationCanceledException when the CancelationToken is canceled? I'm having difficulty reproducing the problem as each scenario in the tests, works.

**Comment by CrazyOrange** [comment]
Weird, setting some debug breakpoints seems to have fixes this "issue". So I guess this was an debugger cause isse. Sorry.
